blank_issues_enabled: false
contact_links:
  - name: Question, idea or general talk
    url: https://github.com/copier-org/copier/discussions
    about: Please share your thoughts or ask and answer questions here.
