name: release

on:
  push:
    branches: [master]
    tags: ["*"]

env:
  # renovate: datasource=devbox depName=uv
  UV_VERSION: "0.8.2"

jobs:
  build:
    name: Build project for distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: ${{ env.UV_VERSION }}

      # See https://peps.python.org/pep-0440/#local-version-identifiers
      - name: Omit local version for publishing to test.pypi.org
        if: github.ref == 'refs/heads/master'
        # HACK: https://github.com/ofek/hatch-vcs/issues/43
        run: |
          cat << EOF >> pyproject.toml

          [tool.hatch.version.raw-options]
          local_scheme = "no-local-version"
          EOF

      - name: Build project for distribution
        run: uv build

      - name: Upload artifact containing distribution files
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          if-no-files-found: error

  publish-test:
    name: Publish package distributions to test.pypi.org
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
    environment:
      name: pypi-test
      url: https://test.pypi.org/p/copier
    permissions:
      id-token: write

    steps:
      - name: Download artifact containing distribution files
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist/

      - name: Upload package distributions
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: https://test.pypi.org/legacy/

  publish:
    name: Publish package distributions to pypi.org
    runs-on: ubuntu-latest
    needs: [publish-test]
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: pypi
      url: https://pypi.org/p/copier
    permissions:
      id-token: write

    steps:
      - name: Download artifact containing distribution files
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist/

      - name: Upload package distributions
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
