name: release

on:
  push:
    branches: [master]
    tags: ["*"]

env:
  # renovate: datasource=pypi depName=uv
  UV_VERSION: "0.6.16"

jobs:
  build:
    name: Build project for distribution
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: ${{ env.UV_VERSION }}

      - name: Build project for distribution
        run: uv build

      - name: Upload artifact containing distribution files
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          if-no-files-found: error

  publish-test:
    name: Publish package distributions to test.pypi.org
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: pypi-test
      url: https://test.pypi.org/p/copier
    permissions:
      id-token: write

    steps:
      - name: Download artifact containing distribution files
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Upload package distributions
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: https://test.pypi.org/legacy/

  publish:
    name: Publish package distributions to pypi.org
    runs-on: ubuntu-latest
    needs: [publish-test]
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: pypi
      url: https://pypi.org/p/copier
    permissions:
      id-token: write

    steps:
      - name: Download artifact containing distribution files
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Upload package distributions
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
